### ISSUE TITLE
Volume conf in docker-compose will overwrite Dockerfile Run

### ISSUE THREAD

**Issue by BrenoMazieiro** [uSouza/graphql-unit-tests#1]
We are doing that on Dockerfile:
COPY package*.json ./
RUN npm install
COPY . .

and then on docker-compose we have:
volumes:
      - './:/usr/src/app:rw'

this means that you will loose the node_modules folder created by Dockerfile, because docker-compose will "put" the folder over the folder in the created image.

**Comment by uSouza** [comment]
Thanks @BrenoMazieiro!
